"""empty message

Revision ID: 260652ac06bc
Revises: f5db4d91efa8
Create Date: 2021-01-05 13:03:39.658476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260652ac06bc'
down_revision = 'f5db4d91efa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
